# This inventory describe a HA typology with stacked etcd (== same nodes as control plane)
# and 3 worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your # inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
master01 ansible_host=10.10.20.61 ip=10.10.20.61 etcd_member_name=etcd1
node01 ansible_host=10.10.20.71 ip=10.10.20.71 etcd_member_name=etcd2
node02 ansible_host=10.10.20.72 ip=10.10.20.72 etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node:children]
kube_control_plane

[kube_node]
# node03 ansible_host=10.10.20.73 ip=10.10.20.73
# node04 ansible_host=10.10.20.74 ip=10.10.20.74
# node05 ansible_host=10.10.20.75 ip=10.10.20.75

[k8s_cluster:children]
kube_control_plane
kube_node
