---
- name: Gather OS information
  setup:
    gather_subset:
      - distribution
      - pkg_mgr

- name: Manage packages
  package:
    name: "{{ item.packages | dict2items | selectattr('value', 'ansible.builtin.all') | map(attribute='key') }}"
    state: "{{ item.state }}"
    update_cache: "{{ true if ansible_pkg_mgr in ['zypper', 'apt', 'dnf'] else omit }}"
    cache_valid_time: "{{ 86400 if ansible_pkg_mgr == 'apt' else omit }}" # 24h
  register: pkgs_task_result
  until: pkgs_task_result is succeeded
  retries: "{{ pkg_install_retries }}"
  delay: "{{ retry_stagger | random + 3 }}"
  when: not (ansible_os_family in ["Flatcar", "Flatcar Container Linux by Kinvolk"] or is_fedora_coreos)
  loop:
    - { packages: "{{ pkgs_to_remove }}", state: "absent", action_label: "remove" }
    - { packages: "{{ pkgs }}", state: "present", action_label: "install" }
  loop_control:
    label: "{{ item.action_label }}"
  tags:
    - bootstrap_os
