---
dependencies:
  - role: network_plugin/cni
    when: kube_network_plugin != 'none'

  - role: network_plugin/cilium
    when: kube_network_plugin == 'cilium' or cilium_deploy_additionally
    tags:
      - cilium

  - role: network_plugin/calico
    when: kube_network_plugin == 'calico'
    tags:
      - calico
