---
# Metrics Server deployment
metrics_server_enabled: true
# metrics_server_container_port: 10250
# metrics_server_kubelet_insecure_tls: true
# metrics_server_metric_resolution: 15s
# metrics_server_kubelet_preferred_address_types: "InternalIP,ExternalIP,Hostname"
# metrics_server_host_network: false
# metrics_server_replicas: 1

# CSI Volume Snapshot Controller deployment, set this to true if your CSI is able to manage snapshots
# Longhorn is an external CSI that would also require setting this to true but it is not included in kubespray
csi_snapshot_controller_enabled: true
# csi snapshot namespace
snapshot_controller_namespace: kube-system
