# noqa role-name - this is a meta role that doesn't need a name
---
dependencies:
  - role: container-engine/validate-container-engine
    tags:
      - container-engine
      - validate-container-engine

  - role: container-engine/containerd
    when:
      - container_manager == 'containerd'
    tags:
      - container-engine
      - containerd

  - role: container-engine/cri-dockerd
    when:
      - container_manager == 'docker'
    tags:
      - container-engine
      - docker
